name: Unit & WCAG Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  discussions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - uses: lowlydba/sustainable-npm@v2

      - run: npm ci

      - name: Unit tests
        run: npm test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Fetch discussions
        run: npm run fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Accessibility tests
        run: npm run test:a11y
